<ul class="nav nav-tabs">
    <li <?php echo $action=='list'?'class="active"':'' ?> >
        <a href="<?php echo $this->url('admin/playgrounddesign_themeadmin'); ?>">Gérer les thèmes</a>
    </li>
    <?php if($action == 'add' || $action == 'list') : ?>
        <li <?php echo $action=='add'?'class="active"':'' ?>>
            <a href="<?php echo $this->url('admin/playgrounddesign_themeadmin_new'); ?>">Ajouter un thème</a>
        </li>
    <?php elseif ($action == 'edit') : ?>
        <li class="active">
            <a href="#">Editer un thème</a>
        </li>
    <?php endif; ?>
    <?php if($automaticTheme > 0) : ?>
        <li class="">
            <a href="#">Valider un thème (<?php echo $automaticTheme; ?>) </a>
        </li>
    <?php endif; ?>
</ul>