Theme de demo
<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounddesign');// Pour le texte ?>
<div class="row-fluid show-grid">
    <?php echo $this->partial('playground-design/partial/menu.phtml', array('action' => 'list', 'automaticTheme' => $automaticTheme)); ?>
    <ul class="thumbnails">
        <?php foreach ($themesActivated as $theme) : ?>
            <li class="span4">
                <div class="thumbnail">
                        <?php foreach ( $theme->getImages() as $image) : ?>
                            <img alt="<?php echo $theme->getTitle(); ?>" data-src="holder.js/300x200" style="width: 300px; height: 200px;" src="<?php echo $image;?>" class="image">
                        <?php endforeach; ?>
                    <div class="caption">
                        <p class="muted"><?php echo $this->translate('Theme actuel'); ?><p>
                        <h3><?php echo $theme->getTitle(); ?> <?php echo $this->translate('de type'); ?> <?php echo $theme->getType(); ?></h3>
                        <p><?php echo $this->translate('par'); ?> <?php echo $theme->getAuthor(); ?></p>
                        <p><?php echo $this->translate('Tous les fichiers de ce thème se trouvent dans');?> <?php echo $theme->getUrlBase();?></p>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
    <hr class="bs-docs-separator">
    <ul class="thumbnails">
        <?php foreach ($themesNotActivated as $theme) : ?>
            <li class="span4">
                <div class="thumbnail">
                    <?php foreach ( $theme->getImages() as $image) : ?>
                        <img alt="<?php echo $theme->getTitle(); ?>" data-src="holder.js/300x200" style="width: 300px; height: 200px;" src="<?php echo $image;?>" class="image">
                    <?php endforeach; ?>
                    <div class="caption">
                        <h3><?php echo $theme->getTitle(); ?> <?php echo $this->translate('de type'); ?> <?php echo $theme->getType(); ?></h3>
                        <p><?php echo $this->translate('par'); ?> <?php echo $theme->getAuthor(); ?></p>
                        <p><?php echo $this->translate('Tous les fichiers de ce thème se trouvent dans');?> <?php echo $theme->getUrlBase(); ?></p>
                        <p>
                            <a class="btn btn-primary" href="<?php echo $this->url('admin/playgrounddesign_themeadmin_activate', array('themeId' => $theme->getId()));?>"><?php echo $this->translate('Activer');?></a>
                            <a class="btn" href="<?php echo $this->url('admin/playgrounddesign_themeadmin_edit', array('themeId' => $theme->getId()));?>"><?php echo $this->translate('Editer');?></a> 
                            <a class="btn" href="<?php echo $this->url('admin/playgrounddesign_themeadmin_delete', array('themeId' => $theme->getId()));?>"><?php echo $this->translate('Supprimer');?></a>
                        </p>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<script>
    $(document).ready(function() {
        $('.thumbnail').each(function(index, elt){
            $(elt).children(".image").each(function(index, img) {
                if (index > 0) {
                    $(img).css('display', 'none');
                }
            });
            $(elt).click(function(event) {
                var imgIndex = 0;
                childElements = $(elt).children(".image");
                childElements.each(function(index, img) {
                    if ($(img).css('display') != 'none') {
                        imgIndex = index;
                        $(img).css('display', 'none');
                        return false;
                    }
                });
                if (imgIndex+1 >= childElements.length) {
                    imgIndex = -1;
                }
                $(childElements[imgIndex+1]).css('display', 'block');

            });
        });
    });  
</script>