<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounddesign');// Pour le texte ?>
<div class="row-fluid show-grid">
    <?php 
        $form = $this->form;
        $form->prepare();
        $type = 'add';
        if($form->get('title')->getValue() != '') {
            $type = 'edit';
        }
        echo $this->partial('playground-design/partial/menu.phtml', array('action' => $type, 'automaticTheme' => $automaticTheme));
        echo $this->form()->openTag($form) 
    ?>
    <div class="span8">
        <?php echo $this->formHidden($form->get('id')); ?>

        <?php echo $this->formLabel($form->get('title')); ?>
        <?php echo $this->formInput($form->get('title')); ?>
        <?php echo $this->formElementErrors($form->get('title')) ?>
        <div id='theme_path'>
            <?php echo $this->formLabel($form->get('theme_path')); ?>
            <strong>/</strong>
            <?php echo $this->formInput($form->get('area')); ?>/<?php echo $this->formInput($form->get('package')); ?>/<?php echo $this->formInput($form->get('theme')); ?>
        </div>
        <?php echo $this->formLabel($form->get('author')); ?>
        <?php echo $this->formInput($form->get('author')); ?>
        <?php echo $this->formElementErrors($form->get('author')) ?>
    </div>
    <div class="span4">
        <div class="thumbnail">
            <?php if($form->get('image')->getValue() != ''):?>
            <?php echo $this->formLabel($form->get('uploadImage')); ?>
            <img  data-src="holder.js/300x200" style="width: 300px; height: 200px;"src="<?php echo $this->basePath($form->get('image')->getValue()); ?>" />
            <?php endif;?>
            <div class="caption">
               <?php echo $this->formFile($form->get('uploadImage')); ?>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <?php echo $this->formButton($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>