<h1><?php echo $this->translate($title); ?></h1>

<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="my-tab-content" class="tab-content">
    <div class="tab-pane active" id="general">
        <div>
            <?php echo $this->formHidden($form->get('id')); ?>

    		<div class="label-input">
                <?php echo $this->formLabel($form->get('title')); ?>
                <?php echo $this->formInput($form->get('title')); ?>
                <?php echo $this->formElementErrors($form->get('title')) ?>
            </div>

    		<div class="label-input">
                <?php echo $this->formLabel($form->get('address')); ?>
                <?php echo $this->formTextarea($form->get('address')); ?>
                <?php echo $this->formElementErrors($form->get('address')) ?>
            </div>

    		<div class="label-input">
                <?php echo $this->formLabel($form->get('twitterAccount')); ?>
                <?php echo $this->formInput($form->get('twitterAccount')); ?>
                <?php echo $this->formElementErrors($form->get('twitterAccount')) ?>
            </div>

    		<div class="label-input">
                <?php echo $this->formLabel($form->get('facebookPage')); ?>
                <?php echo $this->formInput($form->get('facebookPage')); ?>
                <?php echo $this->formElementErrors($form->get('facebookPage')) ?>
            </div>

    		<div class="label-input">
                <?php echo $this->formLabel($form->get('phoneNumber')); ?>
                <?php echo $this->formInput($form->get('phoneNumber')); ?>
                <?php echo $this->formElementErrors($form->get('phoneNumber')) ?>
            </div>

            <div class="label-input file">
                <?php echo $this->formLabel($form->get('uploadMainImage')); ?>
                <?php echo $this->formFile($form->get('uploadMainImage')); ?>
            </div>
            <?php if($form->get('mainImage')->getValue() != ''):?>
            	<img src="<?php echo $this->basePath($form->get('mainImage')->getValue()); ?>" />
            <?php endif;?>
         </div>
     </div>
 </div>